# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "devstack1"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box "
  config.vm.network :private_network, ip: "192.168.2.6"
  config.vm.network :private_network, ip: "172.16.0.206", :netmask => "255.255.0.0"
  config.vm.network :private_network, ip: "10.10.0.206",  :netmask => "255.255.0.0"

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell do |shell|
    shell.inline = "[ ! -f vdone ] && apt-get update && apt-get -y install emacs git vim-gtk libxml2-dev libxslt1-dev libpq-dev python-pip libsqlite3-dev && apt-get -y build-dep python-mysqldb && pip install git-review tox && pip install -U setuptools && git clone git://git.openstack.org/openstack-dev/devstack -b stable/icehouse && chown -R vagrant:vagrant devstack && cp /vagrant/local.conf devstack/local.conf && touch vdone"
  end  
end
