# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.hostname = "packstack1"
  config.vm.box = "centos65-x86_64-20140116"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.vm.network :private_network, ip: "192.168.2.11"
#  config.vm.network :private_network, ip: "172.16.0.206", :netmask => "255.255.0.0"
#  config.vm.network :private_network, ip: "10.10.0.206",  :netmask => "255.255.0.0"

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell, :path => 'bootstrap.sh'
end
